-- ============================================================================
-- Somespai — seed data (imported from mock-spaces.ts)
-- ============================================================================

-- ── Seed owner: a system user to own all seeded spaces ───────────────────────
-- Inserts directly into auth.users for local dev (service-role, no sign-up flow).

INSERT INTO auth.users (
  id, instance_id, aud, role, email, encrypted_password,
  email_confirmed_at, created_at, updated_at,
  raw_app_meta_data, raw_user_meta_data, is_super_admin
) VALUES (
  '00000000-0000-0000-0000-000000000001',
  '00000000-0000-0000-0000-000000000000',
  'authenticated',
  'authenticated',
  'seed@somespai.cat',
  '',
  now(), now(), now(),
  '{"provider":"email","providers":["email"]}',
  '{}',
  false
) ON CONFLICT (id) DO NOTHING;

INSERT INTO profiles (id, display_name)
VALUES ('00000000-0000-0000-0000-000000000001', 'Somespai Seed')
ON CONFLICT (id) DO NOTHING;

-- ── Spaces ───────────────────────────────────────────────────────────────────
-- NOTE: IDs are generated by Postgres (gen_random_uuid()).
-- The slug is the stable external identifier.
-- location = st_makepoint(lng, lat) — note x=lng, y=lat in WGS-84.

INSERT INTO spaces (
  slug, owner_id, title, description, type,
  price_cents, currency, size_m2,
  address, neighborhood, city, region,
  location, amenities, photos,
  is_featured, status, price_unit, contact_url,
  rating, reviews_count
) VALUES

-- 1
(
  'traster-lluminos-lesseps',
  '00000000-0000-0000-0000-000000000001',
  'Traster lluminós a Lesseps',
  $$Traster sec i ben ventilat, accessible 24h amb codi. Cobertura de càmeres a tot l'edifici. Ideal per a caixes, mobles petits i emmagatzematge estacional.$$,
  'storage', 7500, 'EUR', 8,
  'Travessera de Dalt', 'Vila de Gràcia', 'Barcelona', 'Catalunya',
  st_makepoint(2.1497, 41.4045)::geography,
  ARRAY['dry','access_24h','cameras'], ARRAY[]::text[],
  true, 'active', 'month',
  'https://wa.me/34611223344?text=Hola%21+He+vist+el+traster+a+Somespai+i+m%27agradaria+saber-ne+m%C3%A9s.',
  4.8, 12
),

-- 2
(
  'sala-assaig-verdi',
  '00000000-0000-0000-0000-000000000001',
  $$Sala d'assaig al carrer Verdi$$,
  $$Sala insonoritzada per a músics i creadors. Equip de so bàsic inclòs. Llum natural durant els matins, ambient acollidor.$$,
  'workspace', 18000, 'EUR', 22,
  'Carrer de Verdi', 'Vila de Gràcia', 'Barcelona', 'Catalunya',
  st_makepoint(2.1545, 41.4072)::geography,
  ARRAY['soundproofed','pa_system','wifi'], ARRAY[]::text[],
  false, 'active', 'hour',
  $$https://wa.me/34622334455?text=Hola%21+He+vist+la+sala+d%27assaig+a+Somespai+i+m%27agradaria+saber-ne+m%C3%A9s.$$,
  4.6, 28
),

-- 3
(
  'jardi-glicines',
  '00000000-0000-0000-0000-000000000001',
  'Jardí privat amb glicines',
  $$Petit oasi urbà amb glicines centenàries. Perfecte per a sopars íntims, sessions fotogràfiques o tallers a l'aire lliure.$$,
  'garden', 12000, 'EUR', 45,
  'Carrer de Bonavista', 'Vila de Gràcia', 'Barcelona', 'Catalunya',
  st_makepoint(2.1538, 41.4023)::geography,
  ARRAY['water','furniture','bbq'], ARRAY[]::text[],
  true, 'active', 'day',
  'mailto:jardi.glicines@gmail.com',
  5.0, 7
),

-- 4
(
  'placa-diamant-polivalent',
  '00000000-0000-0000-0000-000000000001',
  'Plaça del Diamant — espai polivalent',
  $$Sala diàfana al cor de Gràcia, ideal per a tallers, presentacions o assajos. Cuina petita inclosa, projector disponible.$$,
  'room', 22000, 'EUR', 60,
  'Plaça del Diamant', 'Vila de Gràcia', 'Barcelona', 'Catalunya',
  st_makepoint(2.1565, 41.4032)::geography,
  ARRAY['kitchen','projector','wifi'], ARRAY[]::text[],
  false, 'active', 'hour',
  'https://wa.me/34633445566?text=Hola%21+He+vist+l%27espai+polivalent+a+Somespai+i+m%27agradaria+saber-ne+m%C3%A9s.',
  4.7, 19
),

-- 5
(
  'estudi-creatiu-travessera',
  '00000000-0000-0000-0000-000000000001',
  'Estudi creatiu Travessera',
  $$Estudi compartit amb fibra simètrica, escriptoris regulables i sala de reunions petita. Comunitat tranquil·la, ideal per a treball concentrat.$$,
  'workspace', 26000, 'EUR', 38,
  'Travessera de Gràcia', 'Vila de Gràcia', 'Barcelona', 'Catalunya',
  st_makepoint(2.1583, 41.4012)::geography,
  ARRAY['fiber','fixed_desk','coffee'], ARRAY[]::text[],
  false, 'active', 'month',
  'mailto:estudi.travessera@gmail.com',
  4.5, 15
),

-- 6
(
  'magatzem-pati-camelies',
  '00000000-0000-0000-0000-000000000001',
  $$Magatzem amb pati a Camèlies$$,
  $$Magatzem ampli amb pati per càrrega i descàrrega. Accés furgoneta. Bàscula disponible al lloc.$$,
  'storage', 9500, 'EUR', 14,
  $$Carrer de les Camèlies$$, 'Vila de Gràcia', 'Barcelona', 'Catalunya',
  st_makepoint(2.1601, 41.4099)::geography,
  ARRAY['van_access','scale'], ARRAY[]::text[],
  false, 'active', 'month',
  'https://wa.me/34644556677?text=Hola%21+He+vist+el+magatzem+a+Somespai+i+m%27agradaria+saber-ne+m%C3%A9s.',
  4.4, 9
),

-- 7
(
  'sala-reunions-sol',
  '00000000-0000-0000-0000-000000000001',
  $$Sala de reunions Plaça del Sol$$,
  $$Sala lluminosa per a 6 persones amb vistes a la plaça. Pissarra magnètica, projector i cafè artesà inclòs.$$,
  'workspace', 14000, 'EUR', 18,
  'Plaça del Sol', 'Vila de Gràcia', 'Barcelona', 'Catalunya',
  st_makepoint(2.1546, 41.4039)::geography,
  ARRAY['whiteboard','projector','coffee'], ARRAY[]::text[],
  true, 'active', 'hour',
  'mailto:sala.placacasol@gmail.com',
  4.9, 34
),

-- 8
(
  'hort-urba-compartit',
  '00000000-0000-0000-0000-000000000001',
  $$Hort urbà compartit$$,
  $$Parcel·la d'hort urbà amb eines compartides. Comunitat petita i amable, aigua de pou inclosa.$$,
  'garden', 4500, 'EUR', 20,
  'Carrer de Sostres', 'Vila de Gràcia', 'Barcelona', 'Catalunya',
  st_makepoint(2.1577, 41.4087)::geography,
  ARRAY['water','tools','community'], ARRAY[]::text[],
  false, 'active', 'month',
  'https://wa.me/34655667788?text=Hola%21+He+vist+l%27hort+urb%C3%A0+a+Somespai+i+m%27agradaria+saber-ne+m%C3%A9s.',
  4.7, 11
),

-- 9
(
  'salo-tallers-joanic',
  '00000000-0000-0000-0000-000000000001',
  $$Saló per a tallers a Joanic$$,
  $$Saló acollidor amb terra de fusta. Cadires apilables, llum regulable. Ideal per a ioga, lectures, reunions petites.$$,
  'room', 16000, 'EUR', 32,
  $$Plaça de la Revolució$$, 'Vila de Gràcia', 'Barcelona', 'Catalunya',
  st_makepoint(2.1622, 41.4061)::geography,
  ARRAY['hardwood_floor','stackable_chairs','dimmable_light'], ARRAY[]::text[],
  false, 'active', 'hour',
  'https://wa.me/34666778899?text=Hola%21+He+vist+el+sal%C3%B3+a+Somespai+i+m%27agradaria+saber-ne+m%C3%A9s.',
  4.6, 22
),

-- 10
(
  'garatge-vallcarca',
  '00000000-0000-0000-0000-000000000001',
  'Garatge convertit a Vallcarca',
  $$Garatge sec amb prestatgeries metàl·liques. Càmera de seguretat i accés 24/7 amb codi numèric.$$,
  'storage', 8500, 'EUR', 16,
  'Avinguda de Vallcarca', 'Vila de Gràcia', 'Barcelona', 'Catalunya',
  st_makepoint(2.1481, 41.4119)::geography,
  ARRAY['access_24h','cameras','electricity'], ARRAY[]::text[],
  false, 'active', 'month',
  'https://wa.me/34677889900?text=Hola%21+He+vist+el+garatge+a+Somespai+i+m%27agradaria+saber-ne+m%C3%A9s.',
  4.3, 6
),

-- 11 — Teià
(
  'jardi-oliveres-teia',
  '00000000-0000-0000-0000-000000000001',
  $$Jardí amb oliveres centenàries$$,
  $$Jardí privat de 120 m² envoltat d'oliveres centenàries. Tranquil·litat absoluta amb vistes al Maresme. Perfecte per a celebracions íntimes, sessions fotogràfiques o retirs.$$,
  'garden', 9000, 'EUR', 120,
  'Carrer de Can Garriga', 'Teià', 'Teià', 'Catalunya',
  st_makepoint(2.3178, 41.4901)::geography,
  ARRAY['water','shade','parking'], ARRAY[]::text[],
  true, 'active', 'day',
  'https://wa.me/34688990011?text=Hola%21+He+vist+el+jard%C3%AD+amb+oliveres+a+Somespai+i+m%27agradaria+saber-ne+m%C3%A9s.',
  5.0, 4
),

-- 12
(
  'traster-masia-teia',
  '00000000-0000-0000-0000-000000000001',
  'Traster en masia antiga',
  $$Traster en planta baixa de masia del segle XVIII. Parets de pedra que mantenen la temperatura constant. Accés amb vehicle, elèctricitat inclosa.$$,
  'storage', 6000, 'EUR', 20,
  'Camí de Can Batlle', 'Teià', 'Teià', 'Catalunya',
  st_makepoint(2.3195, 41.4878)::geography,
  ARRAY['dry','van_access','electricity'], ARRAY[]::text[],
  false, 'active', 'month',
  'https://wa.me/34699001122?text=Hola%21+He+vist+el+traster+a+Somespai+i+m%27agradaria+saber-ne+m%C3%A9s.',
  4.6, 8
),

-- 13
(
  'espai-coworking-rural-teia',
  '00000000-0000-0000-0000-000000000001',
  'Espai de treball rural amb terrassa',
  $$Estudi diàfan amb terrassa privada i vistes a la muntanya. Fibra simètrica, aire condicionat, cuina equipada. Silenci i aire net a 20 minuts de Barcelona.$$,
  'workspace', 20000, 'EUR', 35,
  'Carrer Major', 'Teià', 'Teià', 'Catalunya',
  st_makepoint(2.3161, 41.4892)::geography,
  ARRAY['fiber','terrace','ac','kitchen'], ARRAY[]::text[],
  false, 'active', 'month',
  'mailto:espai.teia@gmail.com',
  4.8, 11
),

-- 14
(
  'celler-esdeveniments-teia',
  '00000000-0000-0000-0000-000000000001',
  $$Celler per a tastings i esdeveniments$$,
  $$Celler de pedra amb voltes originals del segle XIX. Temperatura natural de 15°C. Capacitat per a 40 persones, ideal per a tastings de vi, sopars de gala i presentacions exclusives.$$,
  'room', 28000, 'EUR', 55,
  $$Plaça de l'Ajuntament$$, 'Teià', 'Teià', 'Catalunya',
  st_makepoint(2.3208, 41.4869)::geography,
  ARRAY['cellar','dimmable_light','stackable_chairs','audio'], ARRAY[]::text[],
  true, 'active', 'hour',
  'https://wa.me/34611223300?text=Hola%21+He+vist+el+celler+a+Somespai+i+m%27agradaria+saber-ne+m%C3%A9s.',
  4.9, 16
),

-- 15
(
  'terrassa-vistes-mar-teia',
  '00000000-0000-0000-0000-000000000001',
  'Terrassa amb vistes al Mediterrani',
  $$Terrassa elevada amb panoràmica de 180° sobre el Mediterrani i el Maresme. Mobiliari de jardí inclòs, zona de BBQ, accés a piscina exterior. Postes de sol inigualables.$$,
  'garden', 15000, 'EUR', 60,
  'Carrer del Torrent', 'Teià', 'Teià', 'Catalunya',
  st_makepoint(2.3144, 41.4915)::geography,
  ARRAY['sea_view','furniture','bbq','pool'], ARRAY[]::text[],
  false, 'active', 'day',
  'https://wa.me/34622334400?text=Hola%21+He+vist+la+terrassa+a+Somespai+i+m%27agradaria+saber-ne+m%C3%A9s.',
  4.7, 9
),

-- 16 — Sira10
(
  'sira10-sala-verdi',
  '00000000-0000-0000-0000-000000000001',
  'Sira10 — Sala polivalent 35 m²',
  $$Sala diàfana de 35 m² al cor de Gràcia. Ideal per a tallers, presentacions, reunions i esdeveniments petits. Projector Full HD, pissarra magnètica i cuina compartida inclosos. Espais compartits Sira10.$$,
  'room', 19000, 'EUR', 35,
  'Carrer de Verdi, 85', 'Vila de Gràcia', 'Barcelona', 'Catalunya',
  st_makepoint(2.1553, 41.4053)::geography,
  ARRAY['projector','whiteboard','wifi','ac','kitchen','stackable_chairs'], ARRAY[]::text[],
  true, 'active', 'hour',
  'https://wa.me/34600100200?text=Hola%21+He+vist+la+sala+Sira10+a+Somespai+i+m%27agradaria+saber-ne+m%C3%A9s.',
  4.9, 21
),

-- 17
(
  'sira10-coworking-fix',
  '00000000-0000-0000-0000-000000000001',
  'Sira10 — Coworking fixe',
  $$Lloc de coworking fix en espai privat. Comunitat creativa i tranquil·la. Part dels espais compartits Sira10 al carrer Verdi.$$,
  'workspace', 16000, 'EUR', 18,
  'Carrer de Verdi, 85', 'Vila de Gràcia', 'Barcelona', 'Catalunya',
  st_makepoint(2.1553, 41.4053)::geography,
  ARRAY['fiber','fixed_desk','monitor','locker','coffee'], ARRAY[]::text[],
  false, 'active', 'month',
  'https://wa.me/34600100200?text=Hola%21+He+vist+el+coworking+fix+Sira10+a+Somespai+i+m%27agradaria+saber-ne+m%C3%A9s.',
  4.8, 33
),

-- 18
(
  'sira10-coworking-flex',
  '00000000-0000-0000-0000-000000000001',
  'Sira10 — Coworking flexible',
  $$Hot desk per dies o setmanes als espais Sira10. Sense compromís de permanència. Wifi ràpid, cafè i impressora compartits. Entorn tranquil al barri de Gràcia.$$,
  'workspace', 9000, 'EUR', NULL,
  'Carrer de Verdi, 85', 'Vila de Gràcia', 'Barcelona', 'Catalunya',
  st_makepoint(2.1553, 41.4053)::geography,
  ARRAY['wifi','hot_desk','coffee','printer'], ARRAY[]::text[],
  false, 'active', 'day',
  'https://wa.me/34600100200?text=Hola%21+He+vist+el+coworking+flexible+Sira10+a+Somespai+i+m%27agradaria+saber-ne+m%C3%A9s.',
  4.7, 18
),

-- 19 — Coworkings Barcelona
(
  'betahaus-viladomat',
  '00000000-0000-0000-0000-000000000001',
  'Betahaus — coworking i comunitat creativa',
  $$Betahaus és un dels coworkings més consolidats de Barcelona. Espai obert, comunitat internacional de freelancers, startups i creatius. Terrassa, sala d'events i molt bona connexió.$$,
  'workspace', 22000, 'EUR', NULL,
  'Carrer de Viladomat, 175', 'Eixample Esquerra', 'Barcelona', 'Catalunya',
  st_makepoint(2.1527, 41.3831)::geography,
  ARRAY['fiber','meeting_room','terrace','coffee','event_space'], ARRAY[]::text[],
  true, 'active', 'month',
  'https://barcelona.betahaus.com/',
  4.7, 87
),

-- 20
(
  'aticco-pallars-193',
  '00000000-0000-0000-0000-000000000001',
  'Aticco — espai flexible al 22@',
  $$Aticco ofereix coworking flexible i oficines privades al districte tecnològic 22@. Accés 24/7, estudi de podcast, sales de reunions i una comunitat activa d'empreses tech.$$,
  'workspace', 19000, 'EUR', NULL,
  'Carrer de Pallars, 193', 'Poblenou', 'Barcelona', 'Catalunya',
  st_makepoint(2.1976, 41.4013)::geography,
  ARRAY['access_24h','meeting_room','podcast_studio','fiber'], ARRAY[]::text[],
  false, 'active', 'month',
  'https://aticco.com/',
  4.8, 62
),

-- 21
(
  'mob-almogavers',
  '00000000-0000-0000-0000-000000000001',
  'MOB Makers of Barcelona',
  $$Makers of Barcelona és un coworking al cor del 22@ amb gran terrassa exterior. Enfocament en disseny, tecnologia i innovació social.$$,
  'workspace', 17500, 'EUR', NULL,
  $$Carrer dels Almogàvers, 208$$, 'Poblenou', 'Barcelona', 'Catalunya',
  st_makepoint(2.1964, 41.4017)::geography,
  ARRAY['terrace','meeting_room','coffee','wifi'], ARRAY[]::text[],
  false, 'active', 'month',
  'https://www.mob-barcelona.com/',
  4.6, 45
),

-- 22
(
  'onecowork-marina',
  '00000000-0000-0000-0000-000000000001',
  'OneCoWork — Carrer de la Marina',
  $$OneCoWork Marina amb vistes al mar Mediterrani. Espai modern, ben equipat i amb accés 24/7. Comunitat diversa de professionals digitals.$$,
  'workspace', 21000, 'EUR', NULL,
  'Carrer de la Marina, 16', 'Poblenou', 'Barcelona', 'Catalunya',
  st_makepoint(2.1979, 41.3878)::geography,
  ARRAY['sea_view','access_24h','meeting_room','printer_3d'], ARRAY[]::text[],
  false, 'active', 'month',
  'https://www.onecowork.com/',
  4.7, 39
),

-- 23
(
  'utopicus-pallars-85',
  '00000000-0000-0000-0000-000000000001',
  'Utopicus — coworking sostenible',
  $$Utopicus és un coworking amb compromís mediambiental certificat. Disseny biofilíc, materials naturals i comunitat orientada a l'impacte positiu.$$,
  'workspace', 20000, 'EUR', NULL,
  'Carrer de Pallars, 85', 'Poblenou', 'Barcelona', 'Catalunya',
  st_makepoint(2.1900, 41.3955)::geography,
  ARRAY['sustainable','coffee','terrace','bike_parking'], ARRAY[]::text[],
  false, 'active', 'month',
  'https://utopicus.es/',
  4.5, 28
),

-- 24
(
  'cloud-coworking-roger-de-lluria',
  '00000000-0000-0000-0000-000000000001',
  'Cloud Coworking — Eixample',
  $$Coworking acollidor al centre de l'Eixample. Tarifa diària, setmanal i mensual. Bon ambient per a professionals independents i petits equips.$$,
  'workspace', 14000, 'EUR', NULL,
  'Carrer de Roger de Llúria, 49', 'Eixample Dreta', 'Barcelona', 'Catalunya',
  st_makepoint(2.1688, 41.3930)::geography,
  ARRAY['wifi','meeting_room','coffee','printer'], ARRAY[]::text[],
  false, 'active', 'month',
  'mailto:info@cloudcoworking.es',
  4.4, 31
),

-- 25
(
  'talent-garden-llacuna',
  '00000000-0000-0000-0000-000000000001',
  'Talent Garden Barcelona',
  $$Campus de coworking europeu al 22@. Talent Garden Barcelona acull centenars de professionals i startups. Sala d'events fins a 200 persones, formació i xarxa de 30 ciutats europees.$$,
  'workspace', 25000, 'EUR', NULL,
  'Carrer de la Llacuna, 162', 'Poblenou', 'Barcelona', 'Catalunya',
  st_makepoint(2.1928, 41.4061)::geography,
  ARRAY['campus','event_space','podcast_studio','coffee','community'], ARRAY[]::text[],
  true, 'active', 'month',
  'https://talentgarden.com/en/campus/barcelona/',
  4.8, 74
),

-- 26
(
  'crec-consell-de-cent',
  '00000000-0000-0000-0000-000000000001',
  'Crec Coworking — Sants-Montjuïc',
  $$Crec és un coworking de proximitat a Sants, amb terrassa interior i ambient familiar. Ideal per a autònoms i micro-empreses que busquen sortir de casa sense pagar preus d'Eixample.$$,
  'workspace', 13000, 'EUR', NULL,
  'Carrer del Consell de Cent, 159', 'Sants', 'Barcelona', 'Catalunya',
  st_makepoint(2.1543, 41.3827)::geography,
  ARRAY['wifi','kitchen','terrace','meeting_room'], ARRAY[]::text[],
  false, 'active', 'month',
  'https://crec.cat/',
  4.6, 22
),

-- 27
(
  'spaces-diagonal',
  '00000000-0000-0000-0000-000000000001',
  'Spaces — Avinguda Diagonal',
  $$Spaces Diagonal és un coworking premium a l'avinguda més emblemàtica de Barcelona. Recepció professional, sales de reunions d'alt nivell i serveis corporatius complets.$$,
  'workspace', 32000, 'EUR', NULL,
  'Avinguda Diagonal, 477', 'Les Corts', 'Barcelona', 'Catalunya',
  st_makepoint(2.1459, 41.3925)::geography,
  ARRAY['reception','meeting_room','coffee','concierge','access_24h'], ARRAY[]::text[],
  false, 'active', 'month',
  'https://www.spacesworks.com/es/barcelona/',
  4.5, 51
)

ON CONFLICT (slug) DO NOTHING;
